### ISSUE TITLE
Wrong InputOutput field detection

### ISSUE THREAD

**Issue by Stagno** [MeteoSwiss-APN/dawn#1093]
As soon as one field is read and written dawn detects it as `InputOutput`. However this isn't correct. Take as example:
```
nabla2 = ... #First time field nabla2 is referenced, it's a write
nabla2 = nabla2 + ... #Reads nabla2 which was written by the previous write within the same stencil
```
Clearly the value that field `nabla2` had before running the stencil wouldn't matter, because it would be overwritten by the first write.
Thus dawn should classify it as `Output` and not `InputOutput`.
The detection algorithm should: classify as `InputOutput` if a read exists which is not preceded by a write to the same field.

**Comment by Stagno** [comment]
Classification happens here
https://github.com/MeteoSwiss-APN/dawn/blob/6fdc460392e4288f09ed2b81c9d7dfc1798b2437/dawn/src/dawn/IIR/AccessUtils.cpp#L37
and here
https://github.com/MeteoSwiss-APN/dawn/blob/6fdc460392e4288f09ed2b81c9d7dfc1798b2437/dawn/src/dawn/IIR/AccessUtils.cpp#L70
It is not checked whether there was a write before the read.

**Comment by mroethlin** [comment]
Unfortunately this issue turns out to be quite problematic.

* The computation you indicate is happening on the `DoMethod`. Since in unstructured we perform `PassStageSplitAllStatements` we don't have an opportunity to apply the criterion " classify as `InputOutput` if a read exists which is not preceded by a write to the same field" in this place
* We can thus either implement the intent computation as a Pass or as an update method of the IIR tree. The Pass solution requires non modifying the fields stored in the IIR tree from the outside, sacrificing some `const`-ness.   
* An implementation from within the IIR tree seems more appropriate. However `Stencil`, `MultiStage`, `Stage` and `DoMethod` all hold local copies of their fields. Computing the intent at the stencil level requires to propagate the information down the tree (which is a pattern not well supported in dawn)
* A field which may be `InputOutput` at `Stencil` scope may be just `Output` at a smaller scope. This means we either get different answers if we retrieve the Intend from `Stencil` `MultiStage` `Stage` and `DoMethod` or the information stored locally does not reflect the local intent.
* What Intent does a temporary have? The caching pass has strong opinions on that. Also it seems that the Intend information at `DoMethod` Level is used to compute Read and Write `Extent`s. So the information Read/Write/ReadWrite and Input/Output/InputOutput is not clearly distinguished in dawn

**Comment by mroethlin** [comment]
see more detailed discussion here: https://github.com/MeteoSwiss-APN/dawn/issues/1099
