### ISSUE TITLE
Isolate the optimizer from the code that is created to generate valid parallel code

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#395]
The functionality to go from SIR to valid IIR should be a separate step and not be part of the Optimizer. Group the things that are there to impose a parallel model into it's own functionality

**Comment by cosunae** [comment]
I would like to add some thoughts to this, even if I didnt follow the proposed design, so I am not sure if fits. 
Some of the ideas we had was to move all the calls to passes that are needed to generate valid parallel IR into a separate, for example function call like buildValidParallelIR() so that from the injection of the passes we can distinguish them:

https://github.com/MeteoSwiss-APN/dawn/blob/master/dawn/src/dawn/Compiler/DawnCompiler.cpp#L185

Additionally we could manifest this as well in the naming of all the passes
https://github.com/MeteoSwiss-APN/dawn/tree/master/dawn/src/dawn/Optimizer
or move the corresponding ones into another folder ParallelIRBuilder

would it make sense ?

**Comment by mroethlin** [comment]
This has been attempted before. We now want to try this again as a first step towards a more reasonable dawn architecture. The plan for this work item is as follows:

- split the passes into two groups. rerun as many passes as needed to sequentially isolate the passes into two groups
- update, or in the worst case, deactivate tests which are failing due to the wrong order of passes. at the very least, ensure that the gtclang integration tests (codegen) and the gtclang-dycore tests still suceed
- update the infrastructure such that there are two pass managers, one for required, one for optimizing passes.

**Comment by twicki** [comment]
see https://docs.google.com/presentation/d/1KpC15io8NlqTFjQuky1T9fM5T0E25K01_AbbexTu394/edit?usp=sharing
