### ISSUE TITLE
Make dawn gridtype-aware

### ISSUE THREAD

**Issue by lukasm91** [MeteoSwiss-APN/dawn#422]
Even though for many things, dawn doesn't need to know the grid type, overall it should know it.
- Figure out where to put it, is it an option, and HIR concept?
- Implement a way to pass the gridtype to dawn. Maybe infer from `-backend` if possible.
- As a proof of concept, make sure that `MaxHaloPoints` (https://github.com/MeteoSwiss-APN/dawn/blob/master/dawn/src/dawn/Optimizer/OptimizerOptions.inc#L35) is not an int anymore, but an extent (maybe a horizontal extent only?). This doesn't require a change in the frontend of GTClang (we can still take `-max-halo=<N>` and create `HorizontalExtent{ast::cartesian, -maxhalo, maxhalo, -maxhalo, maxhalo}`

**Comment by Stagno** [comment]
My solution to bullet points 1 and 2 would be to make it an SIR and an IIR parameter (see draft https://github.com/MeteoSwiss-APN/dawn/pull/535). You don't need an option, because when you call `DawnCompiler::compile(std::shared_ptr<SIR> const&)` you pass an `SIR` object, whose constructor requires you to specify a grid type.

**Comment by Stagno** [comment]
Regarding point 3:
Right now we only have boolean unstructured offset/extents implemented. I don't think it makes sense to make `MaxHaloPoints` options a `(bool | int)`, but either keep it as it is or maybe make it a string which can be an "extent list":
```
edge->cell->vertex
```
(if the list size is > 1 `hasOffset = true`) or an integer (which would mean a cartesian extent).
No vertical.
