### ISSUE TITLE
Formalize the parallel model 

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#470]
Currently we have the notion of Stages in our parallel model that do not serve a direct cause since there can be stages without sync (meaning they do not enforce synchronization). The only strong requirement they bring is that there can not be two overlapping do-methods in one stage.

There is also the issue with a offset read after write in a MS to fields that can lead to illegal execution that should be specified. 

We should clarify what exactly is meant by any concept. This will probably not affect the user code since there is no notion of parallelism there but we should be precise about our model

**Comment by cosunae** [comment]
I would say the model is the following, 
computations are group into a stage if they do not require synchronization (as you said) and they require the same extent of redundant computations (i.e. the extent of the Stage). 
Indeed two stages might not require synchronization because the separation was triggered by the second condition. 
The first condition is unavoidable, the second is only for performance reasons, but It can be force by activate the StageMerger pass. 

Does this help?
