### ISSUE TITLE
Issue with Access IDs on FieldAccesExpr

### ISSUE THREAD

**Issue by mroethlin** [MeteoSwiss-APN/dawn#591]
## Introduction

The `FieldAccessExpr` inherits an id from `Expr` and stores its name. In the case of nested stencils, both are subject to change. The `StencilDescStatementMapper` inlines nested stencils and uses the `StatementMapper` to do the renaming needed. The `StatementMapper` leaves the ID and Name stored in the `FieldAccessExpr` alone, and instead stores the new ID at
```
expr->getData<iir::IIRAccessExprData>().AccessID = std::make_optional(AccessID);
``` 
The correct name can then be retrieved by means of the `StencilMetaInformation`, the `FieldAccessExpr::Name`member is not updated and remains stale.

It is currently not clear why this is implemented in this way. It seems more natural to simply update the information in place instead of keeping a stale copy of the old data around. Code which relies on this information is error prone, because the correct information is not in the most obvious place.

## Description

The obvious solution of simply adding the following lines 
```
  expr->setID(AccessID); //update ID
  expr->setName(metadata_.getFieldNameFromAccessID(AccessID)); //update Name
```
to `StatementMapper::visit(const std::shared_ptr<iir::FieldAccessExpr>& expr)` leads to out of range accesses in some maps during the compilation of the CodeGen tests. 

## ToDo

Investigate and implement a way to have the above information stored only once, and always up to date.

**Comment by Stagno** [comment]
If I am correct, the ID of an `Expr` is something which is only needed to uniquely identify the expression and for serialization. 
It shouldn't have nothing to do with an `AccessID`, which is a concept specific of IIR and not present in SIR, and since we share the AST code for both SIR and IIR I would say writing
```
expr->setID(AccessID);
```
is incorrect. The `AccessID` should only go in `IIRAccessExprData`. Moreover, in this case, the `AccessID` is the one of a field, so it should be the same for each `FieldAccessExpr`s' `IIRAccessExprData`. The IDs of such expressions, though, should differ, as they are distinct objects of the AST.

For what concerns the name member of the `FieldAccessExpr` I agree that we should keep it in one place only. The problem is that we can't easily get rid, for example, of the `FieldAccessExpr::Name` as it is necessary in SIR to identify the field accessed by the expression (recalling that we don't have `AccessID`s in SIR). We also can't get rid of `AccessIDToNameMap_` in the metadata, as we need a "global" place to retrieve the name from the AccessID (we shouldn't definitely need to go through the AST seeking for a `FieldAccessExpr` accessing the field of which we want to know the name).
Every solution that comes to my mind right now has some flaws. One I would consider acceptable, though, is disabling the name member of the `FieldAccessExpr` in IIR, by putting a `DAWN_ASSERT` in its getter and setter asserting that data is not of IIR type. I don't know if this is easily doable, but I can't think of a better option.

**Comment by Stagno** [comment]
We decided that we want to keep `FieldAccessExpr::Name` updated, even if it's redundant information. Hopefully this won't break the validity of generated code.
