### ISSUE TITLE
rework dawn unit test: dawn/Optimizer/TestXXX

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#779]
does not reflect the folder strucutre, rework

**Comment by mroethlin** [comment]
What we have here are tests of 4 different graph algorithms. All of them are used by some passes (except the partition algorithm, which isn't used anywhere except in the tests). It seems to me that `iir::DependencyGraphAccesses` is misplaced, and should not be part of the `iir` module, but relocated into the optimizer (or optimizer/support or whatever). I.e. the tests are in the correct place, the module being tested isn't.

**Comment by twicki** [comment]
But there is no file "ColoringAlgorithm", so the filename is wrong to start with.

Either move the file (as `TestDependencyGraphAccesses`) to `unit-test/dawn/IIR` or move the graph to `src/dawn/Optmiizer`.

I can live with both options.
The problem with the latter one is though that currently the IR stores Graphs (which can be done with forward declaration) but that would probably move at least one function out? But seems very doable

**Comment by mroethlin** [comment]
Since there are there are other headers related to graphs in the IIR folder (and it doesn't make sense to move only one of them) I decided to simply relocate the tests. I propose to eventually move all Graph algorithm stuff to Support though, since these algorithms are not specific to either IIR nor the optimizer, but could potentially find use in any component.
