### ISSUE TITLE
Remove sirgen dependency in TestPassRemoveScalars

### ISSUE THREAD

**Issue by jdahm** [MeteoSwiss-APN/dawn#812]
TestPassRemoveScalars uses the sirgen utilities https://github.com/MeteoSwiss-APN/dawn/blob/master/dawn/src/dawn/Unittest/UnittestStmtSimplifier.cpp to compare to the form of an IIR statement. This seems broken.

Both DawnUnittest (TestPassRemoveScalars) and GTClangUnittest (TestParsing) use the sirgen utilities, so GTClangUnittest needs to link to DawnUnittest. Building GTClang is built after Dawn (not as a bundle) is currently broken because Dawn (correctly) does not install DawnUnittest.

PR #811 moves these utilities into GTClangUnittest, so these can no longer be used in TestPassRemoveScalars. @Stagno could you please refactor these tests to not use sirgen?

**Comment by Stagno** [comment]
@jdahm sorry, I haven't thought about the dependency on DawnUnittest that this created.
In those test we need to check that the resulting statement is exactly the same as one created on the fly. And having calls such as
```
std::make_shared<dawn::sir::BinaryOperator>(left, op, right)
```
instead of
```
binop(left, op, right)
```
would make the test unreadable, especially when the calls are many:
```
ifstmt(expr(binop(field("f_c"), ">", lit(0.0))), block(),
             block(expr(assign(field("f_c_out"), binop(lit(2.0), "+", lit(1.0))))))
```
I'll move back UnittestStmtSimplifier to GTClangUnittest and add aliases for unit testing in dawn, e.g. 
```
namespace iirgen {
constexpr auto binop = std::make_shared<dawn::iir::BinaryOperator>;
}
```

Or do you have another solution?

**Comment by Stagno** [comment]
@jdahm linked PR does what I suggest, can you review?
